# Generated by Django 6.1 on 2026-08-28 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('governance', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='governancebody',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='governance_bodies', to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='governanceposition',
            name='governance_body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='governance.governancebody', verbose_name='Governance Body'),
        ),
        migrations.AddField(
            model_name='governancepositionassignment',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_assignments', to='organizations.organizationmembership'),
        ),
        migrations.AddField(
            model_name='governancepositionassignment',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='position_assignments', to='governance.governanceposition', verbose_name='position'),
        ),
        migrations.AddConstraint(
            model_name='governancebody',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_governance_body_name_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='governanceposition',
            constraint=models.UniqueConstraint(fields=('governance_body', 'name'), name='unique_position_name_per_governance_body'),
        ),
        migrations.AddConstraint(
            model_name='governancepositionassignment',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='governance_governancepositionassignment_valid_date_period'),
        ),
    ]
