repos:
  - repo: local
    hooks:
      # API
      - id: ruff-check
        name: Ruff check
        entry: poetry -C api run ruff check --fix .
        language: system
        files: ^api/.*\.py$
        pass_filenames: false

      - id: ruff-format
        name: Ruff format
        entry: poetry -C api run ruff format .
        language: system
        files: ^api/.*\.py$
        pass_filenames: false

      # Web
      - id: web-eslint
        name: Web ESLint
        entry: pnpm -C web exec eslint . --fix
        language: system
        files: ^web/.*\.(js|jsx|ts|tsx)$
        pass_filenames: false

      - id: web-prettier
        name: Web Prettier
        entry: pnpm -C web exec prettier --write .
        language: system
        files: ^web/.*\.(js|jsx|ts|tsx|json|css|md)$
        pass_filenames: false

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.16.3
    hooks:
      - id: commitizen
        stages: [commit-msg]
