# Generated by Django 6.1 on 2026-09-06 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('key', models.SlugField(max_length=124, unique=True, verbose_name='key')),
                ('prompt_type', models.CharField(choices=[('system', 'System'), ('input_guardrail', 'Input guardrail'), ('output_guardrail', 'Output guardrail')], max_length=16, verbose_name='prompt type')),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Prompt',
                'verbose_name_plural': 'Prompts',
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PromptGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('key', models.SlugField(max_length=124, unique=True, verbose_name='key')),
            ],
            options={
                'verbose_name': 'Prompt group',
                'verbose_name_plural': 'Prompt groups',
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PromptGroupPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('ordering_index', models.PositiveIntegerField()),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='civic_assistant.prompt', verbose_name='prompt')),
                ('prompt_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='civic_assistant.promptgroup', verbose_name='prompt group')),
            ],
            options={
                'verbose_name': 'Prompt Group Prompt',
                'verbose_name_plural': 'Prompt Group Prompts',
                'ordering': ['prompt_group_id', 'ordering_index'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('prompt_group', 'prompt'), name='unique_prompt_group_prompt'), models.UniqueConstraint(fields=('prompt_group', 'ordering_index'), name='unique_prompt_group_ordering_index')],
            },
        ),
    ]
